name: CredCheck

on:
  workflow_dispatch:

jobs:
  Check-Cred:
    runs-on: windows-2022
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@V1
      with:
        environment-url: 'https://org8afc7726.crm.dynamics.com/'
        user-name: 'admin@M365x639218.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
