# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
            environment-url: 'https://org8afc7726.crm.dynamics.com/'
            user-name: 'admin@M365x639218.onmicrosoft.com'
            password-secret: ${{ secrets.POWERPLATFORM_SOURCEPASSWORD }}
            solution-name: DevOps1
            solution-output-file: ‘DevOps1.zip’
            
      - name: Import Solution
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
            environment-url: 'https://orgd161aeeb.crm4.dynamics.com/'
            user-name: 'admin@M365x639218.onmicrosoft.com'
            password-secret: ${{ secrets.POWERPLATFORM_TARGETPASSWORD }}
            ssolution-file: ‘DevOps1.zip’
            
      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@main
        with:
            environment-url: 'https://orgd161aeeb.crm4.dynamics.com/'
            user-name: 'admin@M365x639218.onmicrosoft.com'
            password-secret: ${{ secrets.POWERPLATFORM_TARGETPASSWORD }}
